int _putchar(char c);
void print_alphabetic(void);
void print_alphabetic_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sigma(int n);
int _abs(*int);
int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
int add(int, int);
int print_to_98(int n);
void print_times_table(int n);
